config/routes.rb
Rails.application.routes.draw do
  

  get 'authorships/create'

  authenticated :user do
  root to: 'books#index', as: :authenticated_root
  end
  root 'home#land'

  devise_for :users

  get 'translate' => 'home#translate', as: :translate

  resources :books do
    resources :chapters, only: [:create, :edit, :update, :destroy] do      
      resources :sections, only: [:create, :show, :update, :edit, :destroy]
    end
    resources :authorships, only: [:create, :update, :destroy]
  end

end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :book
  belongs_to :invitee, class_name: User.name
  belongs_to :invitor, class_name: User.name

  attr_accessor :invitee_email

  after_create :send_authorship_invitation_email

  def accept!
    self.update_attribute(:accepted, true)
  end

  private

      def send_authorship_invitation_email 
        return if self.invitee.skip_authorship_invitation_email      
        AuthorshipMailer.invite(invitee,self).deliver_now
      end


end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController
  before_action :fetch_book
  before_action :fetch_authorship, only: [:update, :destroy]
  def create
    @new_authorship = @book.authorships.new
    authorize! :create, @new_authorship  
    invitee_email = params[:authorship][:invitee_email]
    if ValidateEmail.validate(invitee_email)
      @invitee = User.where(email: invitee_email).first
      if @invitee.nil?
        # flash.now[:danger] = I18n.t'flash_messages.authorships.non_existing_user'
        @invitee = User.invite!({:email => invitee_email}, current_user) do |usr|
          usr.invited_book = @book
        end
        @invitee.skip_authorship_invitation_email = true
        create_invitation
      elsif @invitee.contributing_to(@book)
        flash.now[:danger] = I18n.t'flash_messages.authorships.already_contributor'
      else 
        create_invitation 
      end
    else
      @invalid_email = true
    end
  end

  def update
    authorize! :update, @authorship
    @authorship.accept!
    flash[:success] = I18n.t('flash_messages.authorships.accepted')
    redirect_to root_path

  end

  def destroy    
    authorize! :destroy, @authorship
    @authorship.destroy
    flash[:success] = I18n.t('flash_messages.authorships.rejected')
    redirect_to root_path

  end


  private
      def fetch_book
        @book = Book.find(params[:book_id])
      end

      def fetch_authorship
        @authorship = @book.authorships.find(params[:id])
      end

      def create_invitation        
        @new_authorship.invitee = @invitee
        @new_authorship.invitor = current_user
        @new_authorship.save!
        flash.now[:success] = I18n.t'flash_messages.authorships.invite_success'
      end     

end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/views/authorships/_authorship.html.erb
<div id="authorship">
  <div class="actions pull-right">
    <%= link_to "Accept", book_authorship_path(authorship.book,authorship),method: :patch, class: "btn btn-success btn-sm" %>
    <%= link_to "Reject", book_authorship_path(authorship.book,authorship),method: :delete, class: "btn btn-danger btn-sm" %>
  </div>
  <h4>
  <%= authorship.book.title %>
  </h4>
  <p><%= authorship.book.notes %></p>
  <p>
    Sent by: <%= authorship.invitor.email %> at <%= authorship.created_at.strftime("%v") %>
  </p>
  
</div>
      

app/views/authorships/create.js.erb
$('#invite-author-modal .alert-danger').addClass('hidden');
<% if @invalid_email %>

  $('#invite-author-modal .alert-danger').removeClass('hidden');

<% else %>
  $('#invite-author-modal').modal('hide');
  $('#invite-author-modal form')[0].reset();
  $('header .alert').remove();
  $('header').append('<%= j flash_messages_tag %>');
  
<% end %>