config/routes.rb
Rails.application.routes.draw do
  

  get 'authorships/create'

  authenticated :user do
  root to: 'books#index', as: :authenticated_root
  end
  root 'home#land'

  devise_for :users

  get 'translate' => 'home#translate', as: :translate

  resources :books do
    resources :chapters, only: [:create, :edit, :update, :destroy] do      
      resources :sections, only: [:create, :show, :update, :edit, :destroy]
    end
    resources :authorships, only: [:create, :update, :destroy]
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  belongs_to :owner, class_name: User.name
  has_many :authorships, dependent: :destroy
  validates :title, presence: true
  validates :owner, presence: true

  after_create :make_owner_as_author

  def sorted_chapter_ids=(ids_array)
      
      ids_array = JSON.parse(ids_array)
      grouped_chapters = self.chapters.where(id: ids_array).group_by(&:id)
      index_no = 1
        ids_array.each do |chapter_id|
        chapter_id = chapter_id.to_i
        chapter = grouped_chapters[chapter_id][0]
        chapter.update_attribute(:position, index_no)
        index_no += 1
      end  
  end

  private
      def make_owner_as_author
        invite = self.authorships.new(invitee: self.owner, invitor: self.owner , accepted: true)
        self.owner.skip_authorship_invitation_email = true
        invite.save!
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :authenticate_user!, only: [:index]
  before_action :fetch_book, only: [:show, :destroy, :edit, :update]
  def index
    @new_book = current_user.owned_books.new
    @books = current_user.authoring_books
    @invitations = current_user.authorship_invitations
  end

  def new
    @book= current_user.owned_books.new
    authorize! :create, @book
  end

  def create
    @book = current_user.owned_books.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def show
    authorize! :read, @book
    # flash.now[:success] = "This is a flash message success"
    # flash.now[:danger] = "This is a flash message failure"
    # flash.now[:notice] = "This is a notice flash message"
    # flash.now[:error] = "This is a error flash message"
    @chapters = @book.chapters.includes(:sections).all
    @new_chapter = @chapters.new
    @new_sections = {}
    @chapters.each do |chapter|
      @new_sections[chapter.id] = chapter.sections.new
    end
    @new_authorship = @book.authorships.new
    
  end

  def edit
    authorize! :update, @book
  end

  def update
    authorize! :update, @book
    if @book.update_attributes(book_params)
      
      if params[:book][:sorted_chapter_ids]
        render nothing: true
      else
        flash[:success] = I18n.t 'flash_messages.books.updation_success'
        redirect_to book_path(@book)
      end
    else
      render :edit
    end
  end

  def destroy
    # unless @book.owner == current_user
    #   return deny_access!
    # end
    authorize! :destroy, @book
    if params[:title_confirm].downcase == @book.title.downcase
      @book.destroy
      flash[:success] = I18n.t'flash_messages.books.deletion_success'
      redirect_to books_path
           
    else
      flash[:error] = I18n.t 'flash_messages.books.deletion_error'
      redirect_to book_path(@book)
    end

  end


  private
      def fetch_book
        @book =current_user.authoring_books.find(params[:id])
      end

      def book_params
        params.require(:book).permit(:title, :notes, :sorted_chapter_ids)
      end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>
<%= render 'books/form' %>

app/views/books/index.html.erb
<% if @invitations.any? %>
  <div id="authorship-invitations" class="well">
    <h3>Authorship invitations pending your approval</h3>
    <%= render @invitations %>    
  </div>
<% end %>


<%= link_to "Add a book", new_book_path, class: "btn btn-primary pull-right" if can? :create, @new_book %>
<h1>Select a book to contribute</h1>
<div class="container-fluid">
  <div class="row" id="books">
    <% @books.each do |book| %>
      <div id="book">
        <h3><%= link_to book.title, book_path(book) %></h3>
        
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'books/form' %>

app/views/books/show.html.erb
<div class="container">
  
<section id="book" class="row" data-book-id="<%= @book.id %>">
  <div id="book-content" class="col-md-8 col-md-push-4">
     <h3><%= @book.title %> <%= link_to "Invite Author", "#",class: "btn btn-success btn-sm", data: {toggle: "modal", target: "#invite-author-modal"} if can? :create, @new_authorship%><%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary btn-sm" if can? :update, @book%> <%= link_to "Delete", "#",class: "btn btn-danger btn-sm", data: {toggle: "modal", target: "#delete-confirmation-modal"} if can? :destroy, @book %>  </h3>
    <div id="section-content">
      
    </div>
        
  </div>
  <div id="sidebar" class="col-md-4 col-md-pull-8">
    <div id = "chapters-list"> 
      <%= render @chapters %>
    </div>    
    <%= link_to "+ Add chapter", "#", id: 'new-chapter-form-trigger' if can? :create, @new_chapter%>
    <%= render partial:'chapters/form', locals: {chapter: @new_chapter} %>
  </div>
</section>

</div>

<% if can? :create, @new_authorship %>

  <!--Invite Author Modal confirmation-->
  <div class="modal fade" id="invite-author-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Invite New Author</h4>
        </div>
        <div class="modal-body">
          <p>Please enter the email of the author you would like to invite</p>
          <%= simple_form_for [@book, @new_authorship], remote: true do |f| %>
              <div class="alert alert-danger hidden" role="alert">Please enter a valid email address</div>
              <%= f.input :invitee_email %>            
              <%= f.submit class: "btn btn-primary" %>
          <% end %>   
        </div>      
      </div>
    </div>
  </div>

<% end %>

<% if can? :destroy, @book %>
  <!--Delete Modal confirmation-->
  <div class="modal fade" id="delete-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Are you sure you want to delete?</h4>
        </div>
        <div class="modal-body">
          <p>Please enter the title of book you want to delete and press submit</p>
          <%= form_tag(book_path(@book), method: :delete) do  %>
            <%= text_field_tag(:title_confirm, "", class: "form-control") %>
            <%= submit_tag("Confirm", class: "btn btn-danger") %>
              
          <% end %>
            
          ...
        </div>      
      </div>
    </div>
  </div>

<% end %>