config/routes.rb
Rails.application.routes.draw do
  

  get 'authorships/create'

  authenticated :user do
  root to: 'books#index', as: :authenticated_root
  end
  root 'home#land'

  devise_for :users

  get 'translate' => 'home#translate', as: :translate

  resources :books do
    resources :chapters, only: [:create, :edit, :update, :destroy] do      
      resources :sections, only: [:create, :show, :update, :edit, :destroy]
    end
    resources :authorships, only: [:create, :update, :destroy]
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :sections, dependent: :destroy
  default_scope {order(position: :asc)}
  validates :title, presence: true

  before_create :set_position

  private
      def set_position
        self.position = (self.book.chapters[-2].try(:position) || 0) + 1        
      end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter, only: [:edit,:update,:destroy]

  def create
    @chapter = @book.chapters.new(chapter_params)
    authorize! :create, @chapter
    @save_success = !!@chapter.save
    @new_sections = {@chapter.id => @chapter.sections.new}
    
  end

  def sort    
    ordered_chapter_ids = params[:chapter_ids]
    @grouped_chapters = @book.chapters.where(id: ordered_chapter_ids).group_by(&:id)
    index_no = 1
    ordered_chapter_ids.each do |chapter_id|
      chapter_id = chapter_id.to_i
      chapter = @grouped_chapters[chapter_id][0]
      chapter.update_attribute(:position, index_no)
      index_no += 1
    end

    render nothing: true
  end

  def edit
    authorize! :update, @chapter
  end

  def update
    authorize! :update, @chapter
    @chapter.update_attributes(chapter_params)
    @chapter.reload unless @chapter.valid?
    @new_sections = {@chapter.id => @chapter.sections.new}    
  end

  def destroy
    authorize! :destroy, @chapter
    if @chapter.sections.any?
      flash.now[:danger] = I18n.t'flash_messages.chapters.deletion_failure'
      @destroy_failed = true
    else
      @chapter.destroy
    end
  end


  private
      def fetch_book
        @book = Book.find(params[:book_id])        
      end

      def fetch_chapter
        @chapter = @book.chapters.find(params[:id])
      end

      def chapter_params
        params.require(:chapter).permit(:title,:notes)
      end

end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_chapter.html.erb
<div id = "<%=dom_id chapter %>" class = "chapter clearfix">
  <%= link_to fa_icon('trash'),  book_chapter_path(chapter.book,chapter),method: :delete, remote: true, class: "chapter-delete text-danger", data: {confirm: "Are you sure you want to delete chapter #{chapter.title}?"} if can? :destroy, chapter%>
  <%= link_to fa_icon('pencil'), edit_book_chapter_path(chapter.book,chapter), remote: true, class: "chapter-edit" if can? :update, chapter%>
  <%= link_to "#", remote: true, class: "chapter-title" do %>
    <%= fa_icon 'bars' %>
    <%= fa_icon 'caret-right' %>
    <%= fa_icon 'caret-down' %>

    <%= chapter.title %>
  <% end %>


  <div class="sections">
    <div class="sections-list">
      <%= render chapter.sections %>
    </div>
    <%= link_to "+ Add Section", "#", data: {toggle: "modal", target: "#new-section-modal-#{chapter.id}"} if can? :create, @new_sections[chapter.id]%>  
  </div>
</div>

<% if can? :create, @new_sections[chapter.id] %>

  <!--New section Modal confirmation-->
  <div class="modal fade" id="new-section-modal-<%=chapter.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a Section to <%= chapter.title %></h4>
        </div>
        <div class="modal-body">
          <div class="alert alert-danger hidden" role="alert">
            <%= t'flash_messages.sections.creation_failure' %>
          </div>
          <%= simple_form_for [chapter.book,chapter,@new_sections[chapter.id]], remote: true do |f| %>
              <%= f.input :title %>
              <%= f.input :notes %>
              <%= f.submit class: "btn btn-primary" %>
          <% end %>          
          
          
          
        </div>      
      </div>
    </div>
  </div>

<% end %>

app/views/chapters/_edit_modal.html.erb
<div class="modal fade" id="edit-chapter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Chapter</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "chapters/form", locals: {chapter: @chapter} %>       
          
      
      </div>      
    </div>
  </div>
</div>

app/views/chapters/_form.html.erb
<%= simple_form_for [@book, chapter], html: {id: "new-chapter-form"}, remote: true do |f|%>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.submit class: "btn btn-primary btn-sm" %>
  <%= link_to "Cancel", "#", id: 'cancel-new-chapter-form', class: "btn btn-danger btn-sm" if chapter.new_record? %>
<% end %>

app/views/chapters/create.js.erb
<% if @save_success %>
  $('#new-chapter-form').hide();
  $('#new-chapter-form-trigger').show();
  $('#new-chapter-form')[0].reset();
  $('#chapters-list').append('<%= j render @chapter %>');
  
<% else %>

  $('#new-chapter-form').replaceWith('<%= j render(partial: 'chapters/form', locals: {chapter: @chapter}) %>');
  ChapterUtils.BindNewChapterCancelLink();
<% end %>

app/views/chapters/destroy.js.erb
<% if @destroy_failed %>
  $('header .alert').remove();
  $('header').append('<%= j flash_messages_tag %>');
<% else %>
  $('#<%=dom_id @chapter %>').remove();

<% end %>

app/views/chapters/edit.js.erb
$("#edit-chapter-modal").remove();
$('body').append('<%= j render 'chapters/edit_modal'%>');
$("#edit-chapter-modal").modal('show');

app/views/chapters/update.js.erb
$("#edit-chapter-modal").modal('hide');
$("#<%= dom_id @chapter %>").replaceWith('<%= j render(@chapter)%>');