config/routes.rb
Rails.application.routes.draw do
  

  get 'authorships/create'

  authenticated :user do
  root to: 'books#index', as: :authenticated_root
  end
  root 'home#land'

  devise_for :users

  get 'translate' => 'home#translate', as: :translate

  resources :books do
    resources :chapters, only: [:create, :edit, :update, :destroy] do      
      resources :sections, only: [:create, :show, :update, :edit, :destroy]
    end
    resources :authorships, only: [:create, :update, :destroy]
  end

end

app/views/common/_access.denied.js.erb
console.log("Access denied")

app/views/common/_footer.html.erb
<footer>
  <nav>
    <h4>Chose a language <%= link_to "EN", translate_path(locale: :en) %> | <%= link_to "TE", translate_path(locale: :te) %></h4> 
  </nav>
</footer>

app/views/common/_header.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to APP_NAME, root_path,class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Dashboard", authenticated_root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Signup", new_user_registration_path%></li>
          <li><%= link_to "Login", new_user_session_path, class: "btn btn-success btn-sm" %></li>
        <% end %>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>
<%= flash_messages_tag %>
</header>